# Enable C++ support
language: cpp

# Compiler selection
os: linux
dist: trusty
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake .. && make -j 4